### ISSUE TITLE
Мгновенный повтор

### ISSUE THREAD

**Issue by rhjn13** [SunOner/sunone_aimbot#224]
Наведение всё равно дегранное, как будто программа работает не в полной мере.
В некоторых случаях, если вы экспортировали модель в движок, но в игре всё равно дерганое наведение цены, это помогает включить мнгновенный повтор.
Мгновенный повтор, что это и где включить?

**Comment by SunOner** [comment]
Это теория: Иногда игра/приложение не нагружает видеокарту совсем, и она работает на низких частотах, из за этого приходятся к примеру включать мгновенный повтор от Nvidia experience что бы хоть как то нагрузить её.
Я сталкиваюсь с этой проблемой в Apex и CS2, но когда я включаю что то что бы загрузить видеокарту то аимбот начинает работать во много раз лучше.

**Comment by rhjn13** [comment]
What do I need to enable to download the map?
