### ISSUE TITLE
AttributeError: 'BetterCam' object has no attribute 'is_capturing'

### ISSUE THREAD

**Issue by ChinaVolvocars** [SunOner/sunone_aimbot#227]
P.S. Graphics settings -> find python.exe -> Graphic preference -> Power saving
图形设置 ->python.exe ->图形首选项 节能

![屏幕截图 2024-05-31 222533](https://github.com/SunOner/yolov8_aimbot/assets/11059094/0bfcdc53-c2a0-4332-916d-1d390d076fce)
![屏幕截图 2024-05-31 222612](https://github.com/SunOner/yolov8_aimbot/assets/11059094/54b6c56e-c33f-425b-a669-e8dbc1b10442)

**Comment by NANOBYTECOMPUTERS** [comment]
Set your python to integrated graphics in windows settings https://github.com/SunOner/sunone_aimbot/blob/main/docs/en/install_guide_en.md

**Comment by PointToNorthernstar** [comment]
My problem is that the screen resolution is 3840*2160 caused by the error of reporting ‘’no attribute 'is_capturing' ‘’ , changing to 1280*720 is easy to use, do I have a way to break through this size limit?
