### ISSUE TITLE
Is this right

### ISSUE THREAD

**Issue by MazenNassar** [SunOner/sunone_aimbot#228]
Hi, I was training yolo model and saw those images
are they right?
because when I run the model it doesn't detect any player
![train_batch0](https://github.com/SunOner/yolov8_aimbot/assets/76398875/a9154b59-c4b5-4f43-9b44-c335688f8d15)

![train_batch1](https://github.com/SunOner/yolov8_aimbot/assets/76398875/1cf2d665-2b35-450b-8cc1-c71536296d11)

![train_batch2](https://github.com/SunOner/yolov8_aimbot/assets/76398875/6a89a2c7-3375-4949-b53a-d9001bbab4bc)

**Comment by NANOBYTECOMPUTERS** [comment]
Nope your box is off
