### ISSUE TITLE
你好，关于鼠标移动方面的问题（Machine translation：Hello, I have a question about mouse movement）

### ISSUE THREAD

**Issue by SeeMi157** [SunOner/sunone_aimbot#237]
已知目前的鼠标移动方案是，通过计算屏幕中心到目标位置的偏移量来进行移动，因此当屏幕中心距离目标位置越近，移动时的偏移量就会越低，从而使屏幕中心到达目标位置的速度就会变慢，因此当目标进行移动时，准心很难跟上目标，哪怕速度的数值加大（这只会导准心晃动），因此能否更换一套鼠标移动的方案，使得这个问题解决，无论目标如何移动，准心都能立刻移动到目标中心位置？我了解了一下，貌似通过pid之类的方式可以实现这个方法，但是由于项目的代码结构比较复杂，我目前无法完成这个，55555555...........

Here is the machine translation：
It is known that the current mouse movement scheme is to move by calculating the offset from the center of the screen to the target position. Therefore, when the center of the screen is closer to the target position, the offset during movement will be lower, so that the speed of the center of the screen reaching the target position will be slower. Therefore, when the target moves, it is difficult for the center to keep up with the target. Even if the value of the speed is increased (which only causes the center to shake), can you change a set of mouse movement scheme, so that the problem is solved, no matter how the target moves, the center can immediately move to the center of the target? I have learned about it, it seems that this method can be realized through pid or other ways, but due to the complex code structure of the project, I cannot complete this at present, 55555555...........

**Comment by NANOBYTECOMPUTERS** [comment]
I have submitted a possible patch to allow users to dynamically alter settings to eliminate this issue. PID won't resolve this issue fully due to its heavy reliance of sigmoids.
