### ISSUE TITLE
Управление мышкой

### ISSUE THREAD

**Issue by antinachai9** [SunOner/sunone_aimbot#238]
Взял твою библиотеку ghub_mouse, внедрил в свой проект, именно в варфейсе не работает. МБ я что то проглядел или пофиксили возможность?

**Comment by NANOBYTECOMPUTERS** [comment]
Пользователь GitHub sunone настроил все необходимое для этого проекта и включил его исходный код. Вам нужно выбрать True в настройках, это все. Если у вас есть проблемы, сделайте резервную копию настроек и попробуйте удалить и загрузить бота заново.
