### ISSUE TITLE
help moving mouse WARFACE

### ISSUE THREAD

**Issue by danilkarev** [SunOner/sunone_aimbot#244]
Не двигается мышка в игре Warface, не знаю может у меня настройки какие-то не такие стоят, но определяет ИИ человека нормально, а вот мышка не хочет двигаться на него
https://drive.google.com/file/d/1VkMFVybBQNTfmTQyRredSiGdLjT2TaNL/view?usp=sharing

**Comment by SunOner** [comment]
Стандартный метод ввода не работает в некоторых играх. Для этого нужно использовать другие методы, такие как [Ghub](https://github.com/SunOner/sunone_aimbot?tab=readme-ov-file#mouse) или [Arduino](https://github.com/SunOner/sunone_aimbot?tab=readme-ov-file#mouse).
